### ISSUE TITLE
Need a way to jump back to the toc

### ISSUE THREAD

**Issue by Hoffenbar** [badboy/mdbook-toc#10]
Because the page internal toc isn't shown in another frame and therefore isn't permanently visible (as it is with HUGO´s "book"-Theme) when scrolling down a larger document,  it would be nice if there were a fast way to jump back to the top of the page...
maybe through insertig a link to the toc at every header etc.
Meanwhile I realized that clicking in the top area move to the top. But maybe links here and there where usefull nevertheless.

**Comment by badboy** [comment]
As you've noticed clicking the header jumps to the top and so does hitting the `Home` key.
I don't intend to add more links like you proposed.
