### ISSUE TITLE
Limit the depth of the toc

### ISSUE THREAD

**Issue by Hoffenbar** [badboy/mdbook-toc#11]
Idea: It would be great if one could limit the depth of the headers that were included in the toc, .e.g. only take # and ## into account. Oh, sorry - I overlooked that this is already limited to two levels. But then It would be nice if this was collapsable...

Addition: Level-3 Headers (###) are included in the toc, too - although the doc states that only level-1 and -2 are included...

**Comment by badboy** [comment]
[It's actually 4 layers now!](https://github.com/badboy/mdbook-toc/blob/d4b1a24d071da1d884545b611b37c5b6b944769d/src/lib.rs#L101).

Given that we're gonna have some config soon (#5) we could indeed add that as well.
