### ISSUE TITLE
Non-HTML TOC markers break chapters without TOC

### ISSUE THREAD

**Issue by mlange-42** [badboy/mdbook-toc#13]
When using a TOC marker that is not HTML (as the default marker), chapters without the marker are broken.

Example: Use `[[_TOC_]]` as marker. It may be desired to have chapters without TOC, like an introduction or an appendix. These chapters will have several problems. What I observed so far:

* The page title (i.e. top-level heading like `# Introduction`) disappears
* Tables are broken (Marksdown-Tables as well as HTML tables).

This is what is expected:

![grafik](https://user-images.githubusercontent.com/44003176/106280502-4deffd00-623e-11eb-8e79-048cde256e29.png)

But the result is this:

![grafik](https://user-images.githubusercontent.com/44003176/106280561-64965400-623e-11eb-8aa9-e4ccb625372e.png)

Chapters containing the marker render as expected.

**Comment by badboy** [comment]
Hey, sorry this issue got lost in my inbox.
I'm looking into it.
