### ISSUE TITLE
Enhancement: Ignore white spaces inside "<!-- toc -->" marker

### ISSUE THREAD

**Issue by apatniv** [badboy/mdbook-toc#14]
Thank you creating a very useful crate for generating  toc.

The code expects that user type in exactly `<!-- toc -->` verbatim and if there any spaces after/before toc, it is not recognized as marker. 

For example, this is not recognized as marker
```text
<!--   toc -->
```
I am more than happy to do the changes if you feel if this improves the user experience.

**Comment by badboy** [comment]
I don't think it's worth it. If you specify a marker then that's the marker verbatim. Whitespace _inside_ it is significant and should not be stripped, if anything to reduce complexity of the implementation.

**Comment by apatniv** [comment]
@badboy No problems. Thanks you for the feedback.
