### ISSUE TITLE
headings differing in case are not handled correctly in search

### ISSUE THREAD

**Issue by simonmichael** [badboy/mdbook-toc#16]
This is similar to #15. Eg with headings `tags` and `Tags`, searching for "tags" lists both results but in both cases the link is to #tags. https://hledger.org/hledger.html?search=tags

**Comment by badboy** [comment]
mdbook-toc doesn't handle search. This is probably an upstream issue then.

**Comment by simonmichael** [comment]
Oops, back I go. Thanks.
