### ISSUE TITLE
mdbook-toc failing in GitHub Action with mdBook v0.4.9

### ISSUE THREAD

**Issue by flodolo** [badboy/mdbook-toc#18]
I'm having a weird issue, all of a sudden the action using mdbook-toc is failing across 3 different repositories. Example output from the [latest error](https://github.com/mozilla-l10n/documentation/runs/2752574231?check_suite_focus=true) ([workflow](https://github.com/mozilla-l10n/documentation/blob/master/.github/workflows/deploy.yaml)):

```
2021-06-05 11:01:51 [INFO] (mdbook::book): Book building has started
Unable to parse the input
Error: -05 11:01:51 [ERROR] (mdbook::utils): Error: The "toc" preprocessor exited unsuccessfully with exit code: 1 status
Error: Process completed with exit code 101.
```

Version of packages:
* mdbook v0.4.9
* mdbook-toc 0.6.3
* rust 1.52.1

What's worse is that the generation works fine locally on my machine, with the same versions. Any idea how I could try to debug the issue?

The last time the action worked in one of the repositories, was on May 3rd, using mdbook 0.4.7 and rust 1.51.0

**Comment by flodolo** [comment]
Interestingly enough, it worked fine after forcing v0.4.8 of mdBook
https://github.com/mozilla-l10n/documentation/runs/2752900637?check_suite_focus=true

I have no clue why it would work locally though (macOS vs Linux?)
https://github.com/rust-lang/mdBook/blob/master/CHANGELOG.md#mdbook-049

**Comment by badboy** [comment]
Probably same as https://github.com/badboy/mdbook-mermaid/pull/11, let me get that updated and publish new releases.

**Comment by badboy** [comment]
[0.6.4](https://github.com/badboy/mdbook-toc/releases/tag/0.6.4) is out, built against mdbook 0.4.10

**Comment by flodolo** [comment]
Thanks, it works now 👍🏼
