### ISSUE TITLE
`mdbook-toc` partly breaks CommonMark backslash escapes

### ISSUE THREAD

**Issue by twelho** [badboy/mdbook-toc#21]
Issue originally detailed in https://github.com/rust-lang/mdBook/issues/1620, but I've now figured out that it is this preprocessor causing the issue. CommonMark and mdBook support [backslash escapes](https://spec.commonmark.org/0.30/#backslash-escapes), here's [example 14](https://spec.commonmark.org/0.30/#example-14) from the CommonMark specification (a bit reordered and double spaces appended to each line to force newlines):
```
\*not emphasized*  
\<br/> not a tag  
\[not a link](/foo)  
\`not code`  
\* not a list  
\# not a heading  
\[foo]: /url "not a reference"  
\&ouml; not a character entity  
1\. not a list  
```
Rendering this using mdBook without `mdbook-toc` enabled gives this output, which looks as intended:

![image](https://user-images.githubusercontent.com/38858901/127881015-c7bbf82a-4603-4a3f-9362-25f0ceb0e147.png)

But as soon as `mdbook-toc` version `0.7.0` is enabled using
```toml
[preprocessor.toc]
command = "mdbook-toc"
#marker = "[TOC]" # doesn't matter if set or not
#renderer = ["html"] # doesn't matter if set or not
```
and no matter if the mdBook page contains a table of contents or not the last two escapes stop working:

![image](https://user-images.githubusercontent.com/38858901/127881419-9386c13e-ca75-49f8-825e-fc693ab3fdc8.png)

I presume this is due to some inadvertent "unescaping" (backslash removal) happening in the preprocessor, but it's a bit strange that only numeric lists and character entities are affected. Specifically for numeric lists the current behavior is identical to the backslashes being removed by hand, see https://github.com/rust-lang/mdBook/issues/1620 for another example.

**Comment by badboy** [comment]
ah gosh, round-trip parsing markdown is ... hard and this is a whackamole. I need to see what I can do.
