### ISSUE TITLE
Wrong href for unicode id

### ISSUE THREAD

**Issue by SichangHe** [badboy/mdbook-toc#29]
The specific problem can be observed [here](https://sichanghe.github.io/notes/mathematics/abstract_algebra.html#bézouts-identity).

Please click on the second button on the top-left to see the toc in sidebar. In the sidebar, the anchor that says `Bézout's identity` actually has an `href` of `#b%C3%A9zouts-identity`, but the actual `id` of the corresponding element in the article is `#bézouts-identity`.

- This has the intended effect on the functionality of being a link. That is, it does take you to the correct element in the page after you click it.
- This messes up with my code [here](https://github.com/SichangHe/notes/blob/e3f74089bf1440e2870085970e88fbc90730ad2c/theme/book.js#L704) because I use the `href` in the toc as the `id` to find the corresponding element.

If you need more information, please let me know.

Thank you.
Steven Hé (Sīchàng)

**Comment by badboy** [comment]
Seems like this plugin does everything right ([and it really does just what mdbook does](https://github.com/badboy/mdbook-toc/blob/0ceab3dc7ef0a2ccb2eaf9e98fd39d00d2ac5a01/src/lib.rs#L190)).
Your frontend code is wrong and you should use [`decodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent).

**Comment by SichangHe** [comment]
Thank you for your help! According to your suggestion to use `decodeURIComponent`, I fixed my issue [here](https://github.com/SichangHe/notes/commit/864a77f4c1859bb6c95128dbe1e19866babd56c0).
