### ISSUE TITLE
Support and strip heading attributes

### ISSUE THREAD

**Issue by dnaka91** [badboy/mdbook-toc#39]
Currently, I'm making pretty heaving use of [heading attributes](https://rust-lang.github.io/mdBook/format/markdown.html#heading-attributes), to have custom fragment identifier for my headings.

Sadly, they're currently not handled by mdbook-toc, which causes wrong names in the generated table of contents.

I saw that the `pulldown-cmark` crate has support for this. The necessary steps are probably to add the [Options::ENABLE_HEADING_ATTRIBUTES](https://docs.rs/pulldown-cmark/0.9.3/pulldown_cmark/struct.Options.html#associatedconstant.ENABLE_HEADING_ATTRIBUTES) and then handle the [Tag::Heading](https://docs.rs/pulldown-cmark/0.9.3/pulldown_cmark/enum.Tag.html#variant.Heading) properly.

### Example

The following allows me to have the same header names in different sections, and still have reasonable well named fragment anchors.

```md
# My content

## A

### Schema {#a-schema}

## B

### Schema {#b-schema}
```

Then `mdbook-toc` includes those creating a ToC like this:

```md
- [A](#a)
  - [Schema {#a-schema}](#schema-a-schema)
- [B](#b)
  - [Schema {#b-schema}](#schema-b-schema)
```

What it should render, is the following

```md
- [A](#a)
  - [Schema](#a-schema)
- [B](#b)
  - [Schema](#b-schema)
```

**Comment by badboy** [comment]
Feel free to send a PR handling that.

**Comment by dnaka91** [comment]
Absolutely. Will prepare the changes in the coming days and send it your way 👍

**Comment by badboy** [comment]
Cool, I'll make sure to have some free cycles for review & merge then
